import React from "react";

/**
 * - Header
 * 	- Logo
 * 	- NavItems
 * - Body
 * 	- Search
 *  - RestaurantConatiner
 *  	- RestaurantCard
 * 			- Img
 * 			- Name, Rating,Cuisine
 * - Footer
 * 	- Copyright
 *  - Links
 *  - Address
 *  - Contanct
 *
 */

const resData = [
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "22472",
            name: "Agatya",
            uuid: "9a000eb5-7d68-4105-9993-5a0dda9c324f",
            city: "6",
            area: "Lohegaon",
            totalRatingsString: "10000+ ratings",
            cloudinaryImageId: "phy6a5tvqqtr6enryayd",
            cuisines: [
                "North Indian",
                "Chinese",
                "Seafood",
                "Mughlai",
                "Beverages",
            ],
            tags: [],
            costForTwo: 40000,
            costForTwoString: "₹400 FOR TWO",
            deliveryTime: 49,
            minDeliveryTime: 49,
            maxDeliveryTime: 49,
            slaString: "49 MINS",
            lastMileTravel: 5,
            slugs: {
                restaurant: "agatya-vishrantwadi-vishrantwadi",
                city: "pune",
            },
            cityState: "6",
            address:
                "Agatya, Near Dhanori Jakat Naka, Portal Road, Pune 411047",
            locality: "Dhanori",
            parentId: 27648,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            ribbon: [
                {
                    type: "PROMOTED",
                },
            ],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 4900,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 4900,
                message: "",
                title: "Delivery Charge",
                amount: "4900",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID:
                "cid=6814234~p=1~eid=00000188-3356-d92b-5c30-5c4e004e017a",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "5 kms",
            hasSurge: false,
            sla: {
                restaurantId: "22472",
                deliveryTime: 49,
                minDeliveryTime: 49,
                maxDeliveryTime: 49,
                lastMileTravel: 5,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: true,
            avgRating: "4.0",
            totalRatings: 10000,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "117540",
            name: "Aroma's Hyderabad House",
            uuid: "2d3bc8f2-8cf3-4f58-91cb-63a69e003dd1",
            city: "6",
            area: "Viman Nagar",
            totalRatingsString: "10000+ ratings",
            cloudinaryImageId: "hf6qvqmkb5iduinefdoz",
            cuisines: ["Biryani", "Mughlai", "North Indian", "Chinese"],
            tags: [],
            costForTwo: 50000,
            costForTwoString: "₹500 FOR TWO",
            deliveryTime: 33,
            minDeliveryTime: 33,
            maxDeliveryTime: 33,
            slaString: "33 MINS",
            lastMileTravel: 0.6000000238418579,
            slugs: {
                restaurant: "aromas-hyderabad-house-viman-nagar-viman-nagar",
                city: "pune",
            },
            cityState: "6",
            address:
                "Plot 14, Survey 206/3, Dhantak House, Besides Rosary School, Behind Phoenix Market city, Viman Nagar, Pune",
            locality: "Phoenix Market city",
            parentId: 71,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 3300,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 3300,
                message: "",
                title: "Delivery Charge",
                amount: "3300",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "0.6 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "40% OFF",
                subHeader: "UPTO ₹80",
                discountTag: "",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "117540",
                deliveryTime: 33,
                minDeliveryTime: 33,
                maxDeliveryTime: 33,
                lastMileTravel: 0.6000000238418579,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.2",
            totalRatings: 10000,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "8384",
            name: "Chaitanya Paranthas",
            uuid: "206993ed-27da-4139-a69c-2e80d7fb6c9c",
            city: "6",
            area: "Viman Nagar",
            totalRatingsString: "10000+ ratings",
            cloudinaryImageId: "fubouoxepzalcgmfmwsf",
            cuisines: [
                "North Indian",
                "Punjabi",
                "Chinese",
                "Thalis",
                "Beverages",
                "Desserts",
            ],
            tags: [],
            costForTwo: 25000,
            costForTwoString: "₹250 FOR TWO",
            deliveryTime: 35,
            minDeliveryTime: 35,
            maxDeliveryTime: 35,
            slaString: "35 MINS",
            lastMileTravel: 0.4000000059604645,
            slugs: {
                restaurant:
                    "chaitanya-paranthas-hind-co-op-housing-society-viman-nagar",
                city: "pune",
            },
            cityState: "6",
            address:
                "S . NO . 199+204+205+206/1+209/1,  PLOT NO . 73 , SHOP NO . 10/11/18 ,  GROUND FLOOR, SAI APEX,  LOHEGAON, VIMANNAGAR PUNE ,  Pune Nagar Road & Sangamwadi,  Pune, Maharashtra, 411014",
            locality: "Satyam Marg",
            parentId: 236,
            unserviceable: false,
            veg: true,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 3300,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 3300,
                message: "",
                title: "Delivery Charge",
                amount: "3300",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "0.4 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "30% OFF",
                subHeader: "UPTO ₹75",
                discountTag: "",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "8384",
                deliveryTime: 35,
                minDeliveryTime: 35,
                maxDeliveryTime: 35,
                lastMileTravel: 0.4000000059604645,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.0",
            totalRatings: 10000,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "66309",
            name: "Uncle's Chinese",
            uuid: "500f488f-6294-4047-bf1a-93446e30b5e7",
            city: "6",
            area: "Viman Nagar",
            totalRatingsString: "5000+ ratings",
            cloudinaryImageId: "le6yt8pgom0gx9zi0bwa",
            cuisines: ["Chinese"],
            tags: [],
            costForTwo: 45000,
            costForTwoString: "₹450 FOR TWO",
            deliveryTime: 38,
            minDeliveryTime: 38,
            maxDeliveryTime: 38,
            slaString: "38 MINS",
            lastMileTravel: 1.600000023841858,
            slugs: {
                restaurant:
                    "uncles-chinese-sanjay-park-viman-nagar-viman-nagar",
                city: "pune",
            },
            cityState: "6",
            address: "Sanjay park, Mohammad ali chowk, Viman nagar",
            locality: "Sanjay park",
            parentId: 219488,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            ribbon: [
                {
                    type: "PROMOTED",
                },
            ],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 3300,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 3300,
                message: "",
                title: "Delivery Charge",
                amount: "3300",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID:
                "cid=6666269~p=4~eid=00000188-3356-d92b-5c30-5c4f004e046e",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "1.6 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "₹125 OFF",
                subHeader: "ABOVE ₹499",
                discountTag: "FLAT DEAL",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "66309",
                deliveryTime: 38,
                minDeliveryTime: 38,
                maxDeliveryTime: 38,
                lastMileTravel: 1.600000023841858,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: true,
            avgRating: "4.1",
            totalRatings: 5000,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "15490",
            name: "Zeeshan - Apna Hyderabadi Food",
            uuid: "2ce1007e-83a0-4ed0-bfa2-2e78df40081f",
            city: "6",
            area: "Peshwa Complex",
            totalRatingsString: "10000+ ratings",
            cloudinaryImageId: "de56dffcc29d6ad046285c5b664bda8f",
            cuisines: [
                "Biryani",
                "North Indian",
                "Hyderabadi",
                "Indian",
                "Chinese",
                "Desserts",
                "Beverages",
            ],
            tags: [],
            costForTwo: 40000,
            costForTwoString: "₹400 FOR TWO",
            deliveryTime: 30,
            minDeliveryTime: 30,
            maxDeliveryTime: 30,
            slaString: "30 MINS",
            lastMileTravel: 0.6000000238418579,
            slugs: {
                restaurant: "zeeshan-viman-nagar-viman-nagar",
                city: "pune",
            },
            cityState: "6",
            address:
                "Row House No. 3 & 3A, Nitron Landmark, Anand Vidya Niketan High School Road, Viman Nagar Pune, Maharashtra",
            locality: "Viman Nagar",
            parentId: 2981,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 3300,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 3300,
                message: "",
                title: "Delivery Charge",
                amount: "3300",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "0.6 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "₹150 OFF",
                subHeader: "ABOVE ₹599",
                discountTag: "FLAT DEAL",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "15490",
                deliveryTime: 30,
                minDeliveryTime: 30,
                maxDeliveryTime: 30,
                lastMileTravel: 0.6000000238418579,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "3.9",
            totalRatings: 10000,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "15091",
            name: "Chang's",
            uuid: "793ae2d5-6365-49a0-a208-ae7fc56f7134",
            city: "6",
            area: "King Sport Home",
            totalRatingsString: "10000+ ratings",
            cloudinaryImageId: "gexvwdb1l3masyhjgmo0",
            cuisines: ["Chinese"],
            tags: [],
            costForTwo: 45000,
            costForTwoString: "₹450 FOR TWO",
            deliveryTime: 35,
            minDeliveryTime: 35,
            maxDeliveryTime: 35,
            slaString: "35 MINS",
            lastMileTravel: 0.4000000059604645,
            slugs: {
                restaurant: "changs-viman-nagar-viman-nagar",
                city: "pune",
            },
            cityState: "6",
            address: "King Sport Home 7, Datta Mandir Chowk, Viman Nagar, Pune",
            locality: "Viman Nagar",
            parentId: 6938,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 3300,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 3300,
                message: "",
                title: "Delivery Charge",
                amount: "3300",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "0.4 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "50% OFF",
                subHeader: "UPTO ₹100",
                discountTag: "",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "15091",
                deliveryTime: 35,
                minDeliveryTime: 35,
                maxDeliveryTime: 35,
                lastMileTravel: 0.4000000059604645,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.3",
            totalRatings: 10000,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "678576",
            name: "Blue Tokai Coffee Roasters",
            uuid: "86a6f82b-f94e-4463-a64b-3f5937399a02",
            city: "6",
            area: "Viman Nagar",
            totalRatingsString: "20+ ratings",
            cloudinaryImageId: "26e94f9d24b4e365b11022e052c6643d",
            cuisines: ["Cafe", "Beverages", "American"],
            tags: [],
            costForTwo: 60000,
            costForTwoString: "₹600 FOR TWO",
            deliveryTime: 37,
            minDeliveryTime: 37,
            maxDeliveryTime: 37,
            slaString: "37 MINS",
            lastMileTravel: 2.299999952316284,
            slugs: {
                restaurant:
                    "blue-tokai-coffee-roasters-viman-nagar-viman-nagar",
                city: "pune",
            },
            cityState: "6",
            address:
                "2nd Floor, Survey No- 225, Unit No-K3 Aero  Mall, Pune, Lohegaon,  Pune, Maharashtra  410032",
            locality: "Lohegaon",
            parentId: 2682,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            ribbon: [
                {
                    type: "PROMOTED",
                },
            ],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 3300,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 3300,
                message: "",
                title: "Delivery Charge",
                amount: "3300",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID:
                "cid=6811677~p=7~eid=00000188-3356-d92b-5c30-5c50004e0775",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "2.2 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "20% OFF",
                subHeader: "UPTO ₹50",
                discountTag: "",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "678576",
                deliveryTime: 37,
                minDeliveryTime: 37,
                maxDeliveryTime: 37,
                lastMileTravel: 2.299999952316284,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: true,
            avgRating: "4.0",
            totalRatings: 20,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "50799",
            name: "Pind Punjab",
            uuid: "4d5aa487-5d29-488c-8ed0-e7271b7fea8f",
            city: "6",
            area: "Viman Nagar",
            totalRatingsString: "10000+ ratings",
            cloudinaryImageId: "fu6hew6ih1h8bxgkipip",
            cuisines: [
                "North Indian",
                "Indian",
                "Punjabi",
                "Chinese",
                "Biryani",
                "Thalis",
                "Mughlai",
                "Beverages",
                "Desserts",
            ],
            tags: [],
            costForTwo: 45000,
            costForTwoString: "₹450 FOR TWO",
            deliveryTime: 40,
            minDeliveryTime: 40,
            maxDeliveryTime: 40,
            slaString: "40 MINS",
            lastMileTravel: 0.699999988079071,
            slugs: {
                restaurant: "pind-punjab-koregaon-park-koregaon-park",
                city: "pune",
            },
            cityState: "6",
            address:
                "Pind Punjab , Row House-1, Clover Corner , CCD CHOWK , Konark Nagar , Clover Park , Viman Nagar, Pune",
            locality: "Konark Nagar",
            parentId: 4196,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 3300,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 3300,
                message: "",
                title: "Delivery Charge",
                amount: "3300",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "0.6 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "₹125 OFF",
                subHeader: "ABOVE ₹499",
                discountTag: "FLAT DEAL",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "50799",
                deliveryTime: 40,
                minDeliveryTime: 40,
                maxDeliveryTime: 40,
                lastMileTravel: 0.699999988079071,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.1",
            totalRatings: 10000,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "5928",
            name: "Burger King",
            uuid: "629735b4-2d84-4805-bb11-a2d50672ceb9",
            city: "6",
            area: "Viman Nagar",
            totalRatingsString: "10000+ ratings",
            cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
            cuisines: ["Burgers", "American"],
            tags: [],
            costForTwo: 35000,
            costForTwoString: "₹350 FOR TWO",
            deliveryTime: 56,
            minDeliveryTime: 56,
            maxDeliveryTime: 56,
            slaString: "56 MINS",
            lastMileTravel: 1,
            slugs: {
                restaurant: "burger-king-viman-nagar",
                city: "pune",
            },
            cityState: "6",
            address:
                "Level 2, Food Court , Phoenix Market City Pune , Viman Nagar",
            locality: "Phoenix Market city",
            parentId: 166,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 3300,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 3300,
                message: "",
                title: "Delivery Charge",
                amount: "3300",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "1 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "60% OFF",
                subHeader: "UPTO ₹120",
                discountTag: "",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "5928",
                deliveryTime: 56,
                minDeliveryTime: 56,
                maxDeliveryTime: 56,
                lastMileTravel: 1,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "3.7",
            totalRatings: 10000,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "602605",
            name: "The Betel Leaf Co.",
            uuid: "0bdf5bb7-c84d-40d9-b332-594640f2e36d",
            city: "6",
            area: "Kalyani Nagar",
            totalRatingsString: "50+ ratings",
            cloudinaryImageId: "azw9pugb1fcehg561cc6",
            cuisines: ["Paan", "Desserts", "Indian"],
            tags: [],
            costForTwo: 20000,
            costForTwoString: "₹200 FOR TWO",
            deliveryTime: 47,
            minDeliveryTime: 47,
            maxDeliveryTime: 47,
            slaString: "47 MINS",
            lastMileTravel: 3.9000000953674316,
            slugs: {
                restaurant:
                    "the-betel-leaf-co--originally-from-bangalore-viman-nagar-viman-nagar",
                city: "pune",
            },
            cityState: "6",
            address:
                "219/A-17 MATRUCHAYA H SOCY NAGAR ROAD ,,Pune Nagar Road & Sangamwadi,Pune,Maharashtra-411006",
            locality: "Matruchaya H Socy Nagar Road",
            parentId: 8330,
            unserviceable: false,
            veg: true,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            ribbon: [
                {
                    type: "PROMOTED",
                },
            ],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 4100,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 4100,
                message: "",
                title: "Delivery Charge",
                amount: "4100",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID:
                "cid=6813583~p=10~eid=00000188-3356-d92b-5c30-5c51004e0a61",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "3.9 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "20% OFF",
                subHeader: "UPTO ₹50",
                discountTag: "",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "602605",
                deliveryTime: 47,
                minDeliveryTime: 47,
                maxDeliveryTime: 47,
                lastMileTravel: 3.9000000953674316,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: true,
            avgRating: "4.4",
            totalRatings: 50,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "83060",
            name: "Rasika Pure Veg Restaurant",
            uuid: "ce8f49ed-656a-4c97-856b-d6f9a8a36bb1",
            city: "6",
            area: "Viman Nagar",
            totalRatingsString: "1000+ ratings",
            cloudinaryImageId: "qf8ewbvfz17cvzpk6fvs",
            cuisines: ["North Indian", "Chinese", "South Indian"],
            tags: [],
            costForTwo: 40000,
            costForTwoString: "₹400 FOR TWO",
            deliveryTime: 33,
            minDeliveryTime: 33,
            maxDeliveryTime: 33,
            slaString: "33 MINS",
            lastMileTravel: 0.8999999761581421,
            slugs: {
                restaurant:
                    "rasika-pure-veg-restaurant-viman-nagar-viman-nagar",
                city: "pune",
            },
            cityState: "6",
            address:
                "Shop 5, Siddhivinayak Aurum, behind Eden Garden, Viman Nagar, Pune",
            locality: "Eden Garden Road ",
            parentId: 167210,
            unserviceable: false,
            veg: true,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 3300,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 3300,
                message: "",
                title: "Delivery Charge",
                amount: "3300",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "0.8 kms",
            hasSurge: false,
            sla: {
                restaurantId: "83060",
                deliveryTime: 33,
                minDeliveryTime: 33,
                maxDeliveryTime: 33,
                lastMileTravel: 0.8999999761581421,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.1",
            totalRatings: 1000,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "65583",
            name: "McDonald's",
            uuid: "ab3136d8-f72f-4a16-89bb-9f5f615eb384",
            city: "6",
            area: "Viman Nagar",
            totalRatingsString: "10000+ ratings",
            cloudinaryImageId: "ee5f8e06b300efc07c9fe3f4df40dfc4",
            cuisines: ["Burgers", "Beverages", "Cafe", "Desserts"],
            tags: [],
            costForTwo: 40000,
            costForTwoString: "₹400 FOR TWO",
            deliveryTime: 42,
            minDeliveryTime: 42,
            maxDeliveryTime: 42,
            slaString: "42 MINS",
            lastMileTravel: 1,
            slugs: {
                restaurant: "mcdonalds-kalyani-nagar-viman-nagar",
                city: "pune",
            },
            cityState: "6",
            address:
                "Hardcastle Restaurants Pvt Ltd, McDonalds Family Restaurants Pvt Ltd, Market City-Pune, G-7 Survey No.207, Behind Baker Gauges (I) Pvt Ltd, Next to Tyco Electronics, Nagar Road, Viman Nagar, Pune 4110",
            locality: "Phoenix Market city",
            parentId: 630,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 3300,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 3300,
                message: "",
                title: "Delivery Charge",
                amount: "3300",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "1 kms",
            hasSurge: false,
            sla: {
                restaurantId: "65583",
                deliveryTime: 42,
                minDeliveryTime: 42,
                maxDeliveryTime: 42,
                lastMileTravel: 1,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.2",
            totalRatings: 10000,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "685731",
            name: "Soy Como Soy",
            uuid: "889b28c1-6e9b-49ff-811f-bbfe471709d9",
            city: "6",
            area: "Kalyani Nagar",
            totalRatingsString: "Too Few Ratings",
            cloudinaryImageId: "",
            cuisines: ["Japanese"],
            tags: [],
            costForTwo: 250000,
            costForTwoString: "₹2500 FOR TWO",
            deliveryTime: 52,
            minDeliveryTime: 52,
            maxDeliveryTime: 52,
            slaString: "52 MINS",
            lastMileTravel: 3.700000047683716,
            slugs: {
                restaurant: "soy-como-soy-kalyani-nagar-kalyani-nagar",
                city: "pune",
            },
            cityState: "6",
            address:
                "S . NO. 15/1 FIRST FLOOR BUILDING A GOLDEN NEST CO-OP SOCIETY KALAYANI NAGAR ,Pune Nagar Road & Sangamwadi,Pune,Maharashtra-411014",
            locality: "Sangamwadi",
            parentId: 408927,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            ribbon: [
                {
                    type: "PROMOTED",
                },
            ],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 4100,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 4100,
                message: "",
                title: "Delivery Charge",
                amount: "4100",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID:
                "cid=6660433~p=13~eid=00000188-3356-d92b-5c30-5c52004e0d0d",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "3.7 kms",
            hasSurge: false,
            sla: {
                restaurantId: "685731",
                deliveryTime: 52,
                minDeliveryTime: 52,
                maxDeliveryTime: 52,
                lastMileTravel: 3.700000047683716,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: true,
            avgRating: "--",
            totalRatings: 0,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "264373",
            name: "Gargi snacks",
            uuid: "dce9c939-99a6-4fca-a289-f10bb4de8820",
            city: "6",
            area: "Lohegaon",
            totalRatingsString: "1000+ ratings",
            cloudinaryImageId: "mhgjjk9xzrspb2y9pde6",
            cuisines: ["Snacks"],
            tags: [],
            costForTwo: 15000,
            costForTwoString: "₹150 FOR TWO",
            deliveryTime: 32,
            minDeliveryTime: 32,
            maxDeliveryTime: 32,
            slaString: "32 MINS",
            lastMileTravel: 0.699999988079071,
            slugs: {
                restaurant: "gargi-snacks-viman-nagar-viman-nagar",
                city: "pune",
            },
            cityState: "6",
            address:
                "S NO\t208/1,\tSHOP\tNO 3,LILY AND VIOLATE, CO OP HOUSING SOCIETY, LOHGAON,VIMANNAGAR, LOHGAON PUNE - 411040",
            locality: "Phoenix Mall",
            parentId: 86431,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 3300,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 3300,
                message: "",
                title: "Delivery Charge",
                amount: "3300",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "0.6 kms",
            hasSurge: false,
            sla: {
                restaurantId: "264373",
                deliveryTime: 32,
                minDeliveryTime: 32,
                maxDeliveryTime: 32,
                lastMileTravel: 0.699999988079071,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.5",
            totalRatings: 1000,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "36172",
            name: "Shiv Sagar",
            uuid: "e998ccd6-6438-46a0-b496-8080e3a020bf",
            city: "6",
            area: "Viman Nagar",
            totalRatingsString: "10000+ ratings",
            cloudinaryImageId: "cjgqelua4yuubek2glxr",
            cuisines: ["North Indian", "South Indian", "Chinese"],
            tags: [],
            costForTwo: 40000,
            costForTwoString: "₹400 FOR TWO",
            deliveryTime: 34,
            minDeliveryTime: 34,
            maxDeliveryTime: 34,
            slaString: "34 MINS",
            lastMileTravel: 0.699999988079071,
            slugs: {
                restaurant: "shiv-sagar-viman-nagar-viman-nagar",
                city: "pune",
            },
            cityState: "6",
            address:
                "Ground Floor, A Wing, Lunkad Sky Cruise, West Avenue, Clover Park, Viman Nagar, Pune, Maharashtra 411014",
            locality: "Clover Park",
            parentId: 845,
            unserviceable: false,
            veg: true,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 3300,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 3300,
                message: "",
                title: "Delivery Charge",
                amount: "3300",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "0.6 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "40% OFF",
                subHeader: "UPTO ₹80",
                discountTag: "",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "36172",
                deliveryTime: 34,
                minDeliveryTime: 34,
                maxDeliveryTime: 34,
                lastMileTravel: 0.699999988079071,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.1",
            totalRatings: 10000,
            new: false,
        },
        subtype: "basic",
    },
];


export const Header = () => {
    return (
        <div className="header">
            <div className="logo-container">
                <img
                    src="https://img.freepik.com/premium-vector/online-food-app-icon-food-shop-location-logo-also-online-resturent-location-template_608547-155.jpg?w=700"
                    alt="logo"
                    className="logo"
                />
            </div>
            <div className="nav-items">
                <ul>
                    <li>Home</li>
                    <li>Address</li>
                    <li>Contanct Us</li>
                    <li>Cart</li>
                </ul>
            </div>
        </div>
    );
};

export const RestaurantCard = ({ resData }) => {
    const { name, cuisines, cloudinaryImageId, avgRating, costForTwo , minDeliveryTime } =
        resData.data;

    return (
        <div className="res-card" style={{ backgroundColor: "#f0f0f0" }}>
            <img
                className="res-logo"
                src={`https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/${cloudinaryImageId}`}
                alt="res-logo"
            />
            <h3>{name}</h3>
            <h4>{cuisines.join()}</h4>
            <h4>{avgRating}</h4>
            <h4>₹ {costForTwo / 100} for two </h4>
            <h4>{minDeliveryTime} mins</h4>
        </div>
    );
};

export const Body = () => {
    return (
        <div className="body">
            <div className="search">Search</div>
            <div className="res-container">
                {resData.map((res) => (
                    <RestaurantCard key={res.data.uuid} resData={res} />
                ))}
            </div>
        </div>
    );
};

export const AppLayout = () => {
    return (
        <div className="app">
            <Header />
            <Body />
            //Footer
        </div>
    );
};
